import "./components/collapse";
import "./components/dataToggleClass";
import "./components/dropdown";
import "./components/header";
import "./components/arrows";
import "./components/youtube-embedded";
import "./components/modal";
import "./components/tariffs";
import "./components/goals";
import "./components/form";
import "./components/lazyLoad"
